# Generated by Django 3.0.5 on 2020-11-26 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_lot_no', models.CharField(max_length=100)),
                ('a_deed_no', models.CharField(max_length=100)),
                ('a_sell_order', models.CharField(max_length=100)),
                ('a_law_suit', models.CharField(max_length=100)),
                ('a_type', models.CharField(max_length=100)),
                ('a_rai', models.CharField(max_length=100)),
                ('a_ngan', models.CharField(max_length=100)),
                ('a_wa', models.CharField(max_length=100)),
                ('a_price', models.CharField(max_length=100)),
                ('a_tumbon', models.CharField(max_length=100)),
                ('a_ampur', models.CharField(max_length=100)),
                ('a_province', models.CharField(max_length=100)),
                ('a_ampur_code', models.CharField(max_length=4)),
                ('a_province_code', models.CharField(max_length=5)),
                ('a_law_suit_no', models.CharField(max_length=50)),
                ('a_law_suit_year', models.CharField(max_length=50)),
                ('a_law_court_id', models.CharField(max_length=50)),
                ('is_chanode', models.CharField(max_length=1)),
            ],
        ),
    ]
