# Generated by Django 3.0.5 on 2020-11-27 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='a_addrno',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
